name: Build Docker

on:
  push:
    branches-ignore:
    - master
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test within image
      run: docker build --target test .
